#!/bin/bash
	
echo "Hi! how much time you need this program be in run? (minuates)"
read min

while [[ ! $min =~ ^[0-9]+$ ]];
    do
    echo "Please enter a number:"
    read min
    done


window_id=xdotool xdotool search --name "Telegram"
echo $window_id	

#window_id=104857604

array=(i love you.)
sec=min*60/4

for ((i=1; i<=sec; i++))
   
    do 
    for item in ${array[@]}
        do
        xdotool type  --window $window_id "$item "
        sleep 1
        done

    sleep 1

    if (($i % 10 == 0))
    then
        sleep 10
    fi

        if (($i % 31 == 0))
    then
        sleep 15
    fi

done

exit
‍‍