#!/bin/bash

read -p "Salam! how many minutes is enough for your purpose?" min

# Check if input is a number or not
while [[ ! $min =~ ^-?[0-9]+$ ]];
do
    read -p "Please enter a number:" min
done

# Search for telegram window id
function get_window_id () {
    value= xdotool search --name "Telegram "
    return $value
}

window_id=$(get_window_id)

# Show proper error if telegram is not running.
if [ -z $window_id ];
then
    echo "Error: run telegram and try again."
    exit
fi

# window_id example: 100663300
echo $window_id

# Make an array with statement and convert minutes to seconds
array=(i need you, your are the only one whom i'm in LOVE with.)
sec=min*60/4

# Do the job:) 
for ((i=1; i<=sec; i++))
do 
    for item in ${array[@]}
    do  
        xdotool type --window $window_id "$item "
        sleep 1
    done

    sleep 1

# Simulate human behavior with stop a while
    if (($i % 10 == 0))
    then
        sleep 10
    fi

    if (($i % 37 == 0))
    then
        sleep 15
    fi
done

exit
‍‍
